# Generated by Django 3.2.13 on 2022-05-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_projectmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='dataURI',
        ),
    ]
